import { ApiProperty } from '@nestjs/swagger';
/**
 * This file generated by Apso.
 */

export class LeaseAgreementCreate {
  @ApiProperty()
  agreement_id: string;
  @ApiProperty()
  property_id: number;
  @ApiProperty()
  tenant_id: number;
  @ApiProperty()
  start_date: string;
  @ApiProperty()
  end_date: string;
  @ApiProperty()
  status: string;
}

export class LeaseAgreement {
  @ApiProperty()
  id: number;
  @ApiProperty()
  agreement_id: string;
  @ApiProperty()
  property_id: number;
  @ApiProperty()
  tenant_id: number;
  @ApiProperty()
  start_date: string;
  @ApiProperty()
  end_date: string;
  @ApiProperty()
  status: string;
}
