import { ApiProperty } from '@nestjs/swagger';
/**
 * This file generated by Apso.
 */

export class TenantCreate {
  @ApiProperty()
  tenant_id: string;
  @ApiProperty()
  name: string;
  @ApiProperty()
  email: string;
  @ApiProperty()
  phone_number: string;
  @ApiProperty()
  status: string;
}

export class Tenant {
  @ApiProperty()
  id: number;
  @ApiProperty()
  tenant_id: string;
  @ApiProperty()
  name: string;
  @ApiProperty()
  email: string;
  @ApiProperty()
  phone_number: string;
  @ApiProperty()
  status: string;
}
